name: Network Automation Deploy

on:
  push:
    branches:
      - main  # It will run automatically on every push to the 'main' branch.
  workflow_dispatch:
  
# Automatically cancels old executions if the runner was shut down.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ansible-deploy:
    # Force the pipeline to run exclusively on your local host controller.
    runs-on: [self-hosted, net-control]
    # Runner disconnected, enable timeout
    timeout-minutes: 1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Recreate Vault Password File
        run: |
          # Reconstruir el archivo de clave temporalmente con los permisos restrictivos 600
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > .ansible_vault_pass
          chmod 600 .ansible_vault_pass

      - name: Run Playbook to Switches
        run: |
          # Moverse a root del proyecto
          cd /opt/net-as-code
          
          # Activar el entorno virtual aislado y lanzar el aprovisionamiento
          source .venv/bin/activate
          ansible-playbook site-playbook.yaml -i inventory.yaml -e @vars_secrets.yaml
